feat: add resources for Ethereum
yetanotherco/zero-to-aligned pull request #1
Opened 2024-03-26 05:57 UTC by eminmtas

Just added Ethereum's Whitepaper and some resources about Ethereum

2024-03-26 13:41 UTC, NicolasRampoldi commented on README.md
> +- [Bitcoin: A Peer-to-Peer Electronic Cash System](https://bitcoin.org/bitcoin.pdf) - Bitcoin Whitepaper
It's written white paper not Whitepaper according to this source: [When to Use a Whitepaper - White Paper Style Guide - LibGuides at University of Massachusetts Lowell](https://libguides.uml.edu/whitepaper_style#:~:text=White%20paper%20is%20more%20widely,white%20paper%20is%20the%20standard.)

2024-03-26 13:44 UTC, NicolasRampoldi commented on README.md
> +- [EigenLayer: The Restaking Collective](https://docs.eigenlayer.xyz/assets/files/EigenLayer_WhitePaper-88c47923ca0319870c611decd6e562ad.pdf) - EigenLayer Whitepaper
See comment above

2024-03-26 13:45 UTC, NicolasRampoldi requested changes
Check comments and add full stop to each end of line following the convention already used.

2024-03-26 13:49 UTC, eminmtas commented on README.md
> +- [Bitcoin: A Peer-to-Peer Electronic Cash System](https://bitcoin.org/bitcoin.pdf) - Bitcoin Whitepaper
Just corrected it. Thanks for the info, didn't know that

2024-03-26 13:50 UTC, eminmtas commented
I think it is ready right now. Thanks for the review.

2024-03-27 00:54 UTC, NicolasRampoldi approved these changes

2024-03-27 00:54 UTC, merged